### ISSUE TITLE
DummyOptim' object has no attribute 'step

### ISSUE THREAD

**Issue by avemio-digital** [determined-ai/determined-examples#24]
hello I am facing issue to run llm fine tuning using determined api on my local machine. the error is given below DummyOptim' object has no attribute 'step.  I am using  this one https://github.com/determined-ai/determined-examples/tree/main/blog/llm-finetuning-2

**Comment by KevinMusgrave** [comment]
This was resolved by installing a newer version of `transformers`. See [this slack thread](https://determined-community.slack.com/archives/CV3MTNZ6U/p1721308537247319) for context.
