### ISSUE TITLE
CUDA OOM Issue on large dataset

### ISSUE THREAD

**Issue by avemio-digital** [determined-ai/determined-examples#31]
I am attempting to execute a example script (https://github.com/determined-ai/determined-examples/blob/main/blog/llm-finetuning-3/sft.yaml)  for continual pretraining on a large dataset consisting of approximately 600,000 samples. The script utilizes the DeepSpeed Zero-3 configuration and runs on a system with 8 NVIDIA A100 GPUs. However, despite the available resources, the script encounters a CUDA out-of-memory (OOM) error. The model being utilized is the QWEN2-1.5B model. Could you suggest any modifications to the configuration that would help run the model successfully without experiencing memory issues?

**Comment by ioga** [comment]
resolved through another channel.
